python3 -c 'import os
from stat import *

try:
    os.chdir("mnt")
except Exception as e:
    print(e)
    exit(1)

try:
    os.mknod("file1")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISREG(os.stat("file1").st_mode)
except Exception as e:
    print(e)
    exit(1)

try:
    os.mkdir("d1")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISDIR(os.stat("d1").st_mode)
except Exception as e:
    print(e)
    exit(1)

try:
    os.mknod("d1/file2")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISREG(os.stat("d1/file2").st_mode)
except Exception as e:
    print(e)
    exit(1)

print("Correct")' \
 && ./wfs-check-metadata.py --mode raid1 --blocks 2 --dirs 2 --files 2 --disks test-disk1 test-disk2
