python3 -c 'import os
from stat import *

try:
    os.chdir("mnt")
except Exception as e:
    print(e)
    exit(1)

try:
    os.mkdir("d1")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISDIR(os.stat("d1").st_mode)
except Exception as e:
    print(e)
    exit(1)

print("Correct")' \
 && ./wfs-check-metadata.py --mode raid0 --blocks 1 --altblocks 1 --dirs 2 --files 0 --disks test-disk1 test-disk2 test-disk3
