python3 -c 'import os
from stat import *

try:
    os.chdir("mnt")
except Exception as e:
    print(e)
    exit(1)

print("Correct")' \
 && ./read-write.py 1 50; cat mnt/file1 > file1.test; fusermount -u mnt; ../solution/wfs test-disk3 test-disk2 test-disk1 -s mnt; diff mnt/file1 file1.test && ./wfs-check-metadata.py --mode raid0 --blocks 12 --altblocks 14 --dirs 1 --files 1 --disks test-disk1 test-disk2 test-disk3
